version: 0.1.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore

build:
  project: Simple.sln

after_test:
  - ps: .\.nuget\nugetPack.ps1

artifacts:
  - path: Simple\bin\Release\Simple.dll
    name: Simple.dll
  - path: Simple*.nupkg